// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Good is the predicate function for good builders.
type Good func(*sql.Selector)

// Mission is the predicate function for mission builders.
type Mission func(*sql.Selector)

// Order is the predicate function for order builders.
type Order func(*sql.Selector)

// Record is the predicate function for record builders.
type Record func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
