// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent/dialect/sql"
	"github.com/l1huanyu/x1aol1system/infrastructure/db/ent/good"
)

// Good is the model entity for the Good schema.
type Good struct {
	config
	// ID of the ent.
	ID int `json:"id,omitempty"`
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Good) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case good.FieldID:
			values[i] = new(sql.NullInt64)
		default:
			return nil, fmt.Errorf("unexpected column %q for type Good", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Good fields.
func (_go *Good) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case good.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_go.ID = int(value.Int64)
		}
	}
	return nil
}

// Update returns a builder for updating this Good.
// Note that you need to call Good.Unwrap() before calling this method if this Good
// was returned from a transaction, and the transaction was committed or rolled back.
func (_go *Good) Update() *GoodUpdateOne {
	return (&GoodClient{config: _go.config}).UpdateOne(_go)
}

// Unwrap unwraps the Good entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_go *Good) Unwrap() *Good {
	tx, ok := _go.config.driver.(*txDriver)
	if !ok {
		panic("ent: Good is not a transactional entity")
	}
	_go.config.driver = tx.drv
	return _go
}

// String implements the fmt.Stringer.
func (_go *Good) String() string {
	var builder strings.Builder
	builder.WriteString("Good(")
	builder.WriteString(fmt.Sprintf("id=%v", _go.ID))
	builder.WriteByte(')')
	return builder.String()
}

// Goods is a parsable slice of Good.
type Goods []*Good

func (_go Goods) config(cfg config) {
	for _i := range _go {
		_go[_i].config = cfg
	}
}
