// Code generated by entc, DO NOT EDIT.

package ent

import (
	"github.com/l1huanyu/x1aol1system/infrastructure/db/ent/schema"
	"github.com/l1huanyu/x1aol1system/infrastructure/db/ent/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescCoins is the schema descriptor for coins field.
	userDescCoins := userFields[1].Descriptor()
	// user.DefaultCoins holds the default value on creation for the coins field.
	user.DefaultCoins = userDescCoins.Default.(int64)
	// user.CoinsValidator is a validator for the "coins" field. It is called by the builders before save.
	user.CoinsValidator = userDescCoins.Validators[0].(func(int64) error)
	// userDescID is the schema descriptor for id field.
	userDescID := userFields[0].Descriptor()
	// user.IDValidator is a validator for the "id" field. It is called by the builders before save.
	user.IDValidator = userDescID.Validators[0].(func(string) error)
}
