// Code generated by entc, DO NOT EDIT.

package ent

import (
	"github.com/l1huanyu/x1aol1system/ent/schema"
	"github.com/l1huanyu/x1aol1system/ent/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescUniqueID is the schema descriptor for unique_id field.
	userDescUniqueID := userFields[1].Descriptor()
	// user.UniqueIDValidator is a validator for the "unique_id" field. It is called by the builders before save.
	user.UniqueIDValidator = userDescUniqueID.Validators[0].(func(string) error)
}
